### ISSUE TITLE
can't work in neovim 0.1.7

### ISSUE THREAD

**Issue by luofish** [lambdalisue/lista.nvim#3]
use vim-plug to install

`Plug 'lambdalisue/lista.nvim'`

error happens when use :Lista

function <SNR>68_start[1]..lista#start

E117: Unknown function: _lista_start
E15: _lista_start(a:default)

**Comment by lambdalisue** [comment]
`:UpdateRemotePlugins` and then restart your neovim. It may help.

**Comment by luofish** [comment]
It works, thanks for this wonderful plugin!
