### ISSUE TITLE
Map C-j and C-k to select_previous/next_candidate

### ISSUE THREAD

**Issue by jbuchermn** [lambdalisue/lista.nvim#5]
Is there a way to achieve that?

I tried

`let g:lista#custom_mappings = [ ['<C-k>', '<lista:select_previous_candidate>', 'noremap'], ['<C-j>', '<lista:select_next_candidate>', 'noremap'] ]`

but this did not work. I think, the reason is, that C-j and C-k get remapped when the plugin is initialised, i. e. after my init.vim.

Thank you in advance
Jonas

**Comment by lambdalisue** [comment]
It should work. I'll confirm. In case, could you give me which Vim do you use?

**Comment by jbuchermn** [comment]
I'm using Neovim v0.2.2.

**Comment by lambdalisue** [comment]
And where did you set that variable? Lista does not support dynamic remapping so you have to set that before you use lista

**Comment by jbuchermn** [comment]
In my init.vim.

Just tried this on a clean init.vim, and it worked, so there is some other mistake I am making. Thanks for your time and sorry ;)

**Comment by lambdalisue** [comment]
Good news.
